package com.domain.pinyin;

import java.util.HashMap;
import java.util.Map;

public class Han {
	public static Map<String, String []> han = null;
	
	
	final static String han_fang [] = {"��","��","��","��","��","��","��","��","��","��","��","��","��"};
	final static String han_feng [] = {"��","��","��","��","��","��","��","��","��","��","ٺ","��","��","��","��","��"};
	final static String han_fei [] = {"��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","�","��","��","��"};
	final static String han_fen [] = {"��","��","��","��","��","��","��","��","��","��","��","��","��","��"};
	final static String han_fan [] = {"��","��","��","��","��","��","��","��","��","��","��","��","��","�","ެ","��","��","��"};
	final static String han_fou [] = {"��"};
	final static String han_fo [] = {"��"};
	final static String han_fa [] = {"��","��","��","��","��","��","��","��"};
	final static String han_fu [] = {"��","��","��","��","��","��","��","��","��","��","��","��","ܽ","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��"};
	final static String han_guang [] = {"��","��","��"};
	final static String han_geng [] = {"��","��","��","��","��","��","��"};
	final static String han_gong [] = {"��","��","��","��","��","��","��","��","��","��","��","��","��","��","��"};
	final static String han_guai [] = {"��","��","��"};
	final static String han_guan [] = {"��","��","��","��","��","��","ݸ","��","��","��","��"};
	final static String han_gang [] = {"��","��","��","��","��","��","��","��","��"};
	final static String han_gan [] = {"��","��","��","��","��","��","��","��","��","��","��"};
	final static String han_gai [] = {"ؤ","��","��","��","��","��","��"};
	final static String han_gou [] = {"��","��","��","��","��","ڸ","��","��","��","��","��"};
	final static String han_gua [] = {"��","��","��","��","��","��","��"};
	final static String han_gao [] = {"��","��","��","��","��","��","��","��","��"};
	final static String han_gei [] = {"��"};
	final static String han_gen [] = {"��","��"};
	final static String han_gui [] = {"��","��","��","��","��","��","��","��","��","��","��","��","��"};
	final static String han_gun [] = {"��","��"};
	final static String han_guo [] = {"��","��","��","��","��","��","��","��","��"};
	final static String han_ga [] = {"��","��"};
	final static String han_gu [] = {"��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��"};
	final static String han_ge [] = {"��","��","��","��","��","��","��","��","��","��","��","��","��","��","��"};
	final static String han_dang [] = {"��","��","��","��","��"};
	final static String han_deng [] = {"��","��","��","��","��","��","��"};
	final static String han_dian [] = {"��","��","��","��","��","��","��","��","��","��","��","��","��","�"};
	final static String han_diao [] = {"��","��","��","��","��","��","��","��","��","��"};
	final static String han_ding [] = {"��","��","��","��","��","��","��","��","��","��"};
	final static String han_dong [] = {"��","��","��","��","��","��","��","��","��","��"};
	final static String han_duan [] = {"��","��","��","��","��","��"};
	final static String han_dia [] = {};
	final static String han_dai [] = {"��","��","��","��","�","��","��","��","��","��","��","��","��"};
	final static String han_dao [] = {"��","߶","��","��","��","��","��","��","��","��","��","��"};
	final static String han_die [] = {"��","��","��","��","�","�","��","��","��"};
	final static String han_den [] = {};
	final static String han_diu [] = {"��"};
	final static String han_dei [] = {"��"};
	final static String han_dou [] = {"��","��","��","��","��","��","��","��","��"};
	final static String han_dan [] = {"��","��","��","��","��","��","��","��","��","��","��","��","�","��","��"};
	final static String han_dui [] = {"��","��","��","��","��","�"};
	final static String han_dun [] = {"��","��","��","��","��","��","��","��","��"};
	final static String han_duo [] = {"��","��","��","��","��","��","��","��","��","��","��","��","��","��"};
	final static String han_di [] = {"��","��","��","ۡ","ڮ","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��"};
	final static String han_de [] = {"��","��","�","��"};
	final static String han_da [] = {"��","��","��","�","�","��","��","��","��","��","�"};
	final static String han_du [] = {"��","��","��","��","��","��","��","��","��","��","��","��","��","�","��","��","��"};
	final static String han_eng [] = {};
	final static String han_en [] = {"��","��"};
	final static String han_ei [] = {};
	final static String han_er [] = {"��","��","��","��","��","��"};
	final static String han_e [] = {"��","��","��","��","�","��","��","Ŷ","��","��","��","��","��","ج"};
	final static String han_bang [] = {"��","��","��","��","��","��","��","��","��"};
	final static String han_beng [] = {"��","��","��","��","��","��"};
	final static String han_bing [] = {"��","��","��","��","��","��","��","��","��","��","��"};
	final static String han_bian [] = {"��","��","��","��","��","��","��","��","��","��","��"};
	final static String han_bai [] = {"��","��","��","��","��","İ","��","��","��","��"};
	final static String han_ban [] = {"��","��","��","��","��","��","��","��","��","��","��","��","��","��","��"};
	final static String han_bao [] = {"��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��"};
	final static String han_bei [] = {"��","��","��","��","��","��","��","��","��","�","��","��","��","��","��","��","��"};
	final static String han_ben [] = {"��","��","��","��"};
	final static String han_bie [] = {"��","��","��","��"};
	final static String han_bin [] = {"��","��","��","��","��","��","��","��","��","��"};
	final static String han_bi [] = {"ذ","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","�"};
	final static String han_bo [] = {"��","��","��","��","��","��","��","��","��","��","��","��","��","�","��","��","��","��","��","��","��","��","ެ","��","��","��"};
	final static String han_bu [] = {"��","��","��","��","��","��","��","��","��","��","��"};
	final static String han_ba [] = {"��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��"};
	final static String han_chuang [] = {"��","��","��","��","��","��","��"};
	final static String han_chang [] = {"��","��","��","��","��","��","��","��","��","��","��","��","�","��","��"};
	final static String han_cheng [] = {"ة","��","��","��","��","��","��","��","��","��","ʢ","��","��","��","��","��"};
	final static String han_chong [] = {"��","��","��","��","��","��","��","�"};
	final static String han_chuan [] = {"��","��","��","��","��","��"};
	final static String han_chuai [] = {"�","��"};
	final static String han_ceng [] = {"��","��","��"};
	final static String han_cang [] = {"��","��","��","��"};
	final static String han_cong [] = {"��","��","��","��","��","��"};
	final static String han_chai [] = {"��","��","��","��","��"};
	final static String han_chan [] = {"��","��","��","��","�","��","��","��","��","��","��","��","��","�"};
	final static String han_chao [] = {"��","��","��","��","��","��","��","��","��","��","��"};
	final static String han_cuan [] = {"��","��","��","��"};
	final static String han_chen [] = {"��","��","��","��","��","��","��","��","��","��","��","��"};
	final static String han_chou [] = {"��","��","��","��","�","��","��","��","��","��","��","��","��"};
	final static String han_chua [] = {};
	final static String han_chui [] = {"��","��","��","��","׵","��","�"};
	final static String han_chun [] = {"��","��","��","��","��","��"};
	final static String han_chuo [] = {"�","�","��","��"};
	final static String han_chi [] = {"��","��","߳","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��"};
	final static String han_cou [] = {"��","�","��"};
	final static String han_chu [] = {"��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��"};
	final static String han_che [] = {"��","��","��","��","��"};
	final static String han_cha [] = {"��","��","��","ɲ","��","��","��","��","��","��","��","��","�","��","��"};
	final static String han_cui [] = {"��","��","��","��","��","��","��","�"};
	final static String han_cun [] = {"��","��","��"};
	final static String han_cuo [] = {"��","��","��","��","�","��","��","��","��","��"};
	final static String han_can [] = {"��","��","��","��","��","��","��","��"};
	final static String han_cai [] = {"��","��","��","��","��","��","��","��","��","��","��"};
	final static String han_cen [] = {"�"};
	final static String han_cao [] = {"��","��","��","��","��"};
	final static String han_ca [] = {"��","��","��"};
	final static String han_ce [] = {"��","��","��","��","��","��"};
	final static String han_cu [] = {"��","��","��","�","��","��"};
	final static String han_ci [] = {"��","��","��","��","��","��","��","��","��","��","��","��","��","��"};
	final static String han_ang [] = {"��"};
	final static String han_an [] = {"��","��","��","��","��","��","��","��","��","��"};
	final static String han_ao [] = {"ز","��","��","��","��","��","�","��","��","��","��","��"};
	final static String han_ai [] = {"��","��","��","��","��","��","��","��","��","��","��","��","��","��"};
	final static String han_a [] = {"��","��","��"};
	final static String han_niang [] = {"��"};
	final static String han_neng [] = {};
	final static String han_nian [] = {"��","��","��","ճ","��","շ","��","��"};
	final static String han_nang [] = {};
	final static String han_niao [] = {"��","��","��"};
	final static String han_ning [] = {"��","��","��","š","��"};
	final static String han_nong [] = {"ũ","Ū","ٯ","Ũ","ŧ"};
	final static String han_nuan [] = {"ů"};
	final static String han_nao [] = {"��","��","��","ث","��","�"};
	final static String han_nei [] = {"��"};
	final static String han_nie [] = {"��","��","��","��","��","��","��"};
	final static String han_nin [] = {};
	final static String han_nen [] = {"�"};
	final static String han_niu [] = {"ţ","�","Ť","Ŧ","��","ť"};
	final static String han_nan [] = {"��","��","��","��","��","�","�","��"};
	final static String han_nou [] = {};
	final static String han_nai [] = {"��","ܵ","��","��","٦","��","��","��","��"};
	//final static String han_n��e [] = {};
	final static String han_nuo [] = {"��","Ų","��","ŵ","��","ų","Ŵ"};
	final static String han_nun [] = {};
	final static String han_nu [] = {"ū","Ŭ","��","��","ŭ"};
	//final static String han_n�� [] = {};
	final static String han_na [] = {"��","��","��","��","��","��","��","��","��","��"};
	final static String han_ng [] = {};
	final static String han_ni [] = {"��","��","��","��","��","��","��","��","��","��","��","��","��"};
	final static String han_ne [] = {"ګ","��","��","��"};
	final static String han_ou [] = {"ک","Ż","Ž","ŷ","Ź","Ÿ","ż","��","ź"};
	final static String han_o [] = {"Ŷ"};
	final static String han_liang [] = {"��","��","��","��","��","��","��","��","��","��","��","��","��"};
	final static String han_leng [] = {"��","ܨ","�","��","��"};
	final static String han_lian [] = {"��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","�","��","��","��","�","�","��","�"};
	final static String han_lang [] = {"��","��","��","��","��","��"};
	final static String han_liao [] = {"��","��","��","��","��","��","��","��","��","��"};
	final static String han_ling [] = {"��","��","��","��","��","��","��","��","��","��","��","��","�","��","��","��","��","��","��"};
	final static String han_long [] = {"��","¤","Ū","��","��","£","¢","��","¡","��","��"};
	final static String han_luan [] = {"��","��","��","�"};
	final static String han_lao [] = {"��","��","��","��","��","��","��","��","��","��","��"};
	final static String han_lei [] = {"��","��","ڳ","��","��","��","��","��","��","��","��","��","��","��","��"};
	final static String han_lie [] = {"��","��","��","��","�","��","��","��","��","��","��"};
	final static String han_lin [] = {"��","��","��","��","��","��","��","��","��","��","��","��"};
	final static String han_lan [] = {"��","�","��","��","��","��","��","��","��","��","��","��","�","��","��","��"};
	final static String han_liu [] = {"��","��","½","�","��","��","��","��","��","��","��","µ","��","��"};
	final static String han_lia [] = {};
	final static String han_lou [] = {"ª","¦","§","¥","©","��","��","¶"};
	final static String han_lai [] = {"��","��","��","��","��","�","��"};
	final static String han_lue [] = {};
	//final static String han_l��e [] = {};
	final static String han_lun [] = {"��","��","��","��","��","��"};
	final static String han_luo [] = {"��","��","��","��","��","��","��","��","��","��","��","��","��","��","��"};
	final static String han_le [] = {"��","��","��"};
	final static String han_li [] = {"��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","ٳ","��","��","��","��","ݰ","��","��","�","��","��","��","��","��","��","��","��","��","��","��","��","��","��","�","��"};
	final static String han_la [] = {"��","��","��","��","��","��","��","��","��"};
	final static String han_lu [] = {"��","¬","½","±","«","®","¯","¼","��","��","¸","�","��","­","°","¹","³","»","·","��","µ","¾","ߣ","��","¶"};
	//final static String han_l�� [] = {};
	final static String han_mang [] = {"â","æ","å","ä","ã","ç"};
	final static String han_meng [] = {"��","��","��","��","��","��","��"};
	final static String han_mian [] = {"��","��","��","��","��","��","��","��"};
	final static String han_miao [] = {"��","��","��","��","��","��","��","��"};
	final static String han_ming [] = {"��","��","��","��","ڤ","��","��"};
	final static String han_men [] = {"��","��","��","��","��"};
	final static String han_man [] = {"��","��","��","��","á","��","�","��","��","��","ܬ","��","��"};
	final static String han_mai [] = {"��","��","��","��","��","��","��"};
	final static String han_mao [] = {"ë","ì","é","ï","��","ó","ð","��","è","ñ","ò"};
	final static String han_mie [] = {"��","��","��","��"};
	final static String han_min [] = {"��","��","��","��","��","��","��","��"};
	final static String han_mei [] = {"ÿ","û","��","õ","ö","��","ü","��","ݮ","÷","��","��","ý","��","ú","þ","ø","��","ù","��"};
	final static String han_miu [] = {"��","��"};
	final static String han_mou [] = {"Ĳ","ĳ","ı","��"};
	final static String han_ma [] = {"��","��","��","��","��","Ĩ","��","��","��","��","�"};
	final static String han_mi [] = {"��","��","��","��","��","��","��","��","��","��","�","��","��","��"};
	final static String han_mo [] = {"��","��","ĩ","û","Ĩ","��","İ","ð","Ī","��","��","į","��","��","��","Į","ģ","Ĥ","ġ","��","ī","Ĭ","ĥ","Ģ","ħ"};
	final static String han_me [] = {"ô"};
	final static String han_mu [] = {"ľ","ĸ","Ŀ","Ĳ","ĵ","Ķ","��","ķ","Ĵ","��","ļ","Ļ","Ĺ","��","ģ","ĺ","Ľ","��"};
	final static String han_jiang [] = {"��","��","��","��","��","��","��","��","��","��","��","ǿ","��","��","��","��"};
	final static String han_jiong [] = {"��","��","��","��"};
	final static String han_jiao [] = {"��","��","��","��","��","ٮ","�","��","��","��","��","��","��","��","��","��","��","��","У","��","��","��","��","��","��","��","��","��","��","��","��","��"};
	final static String han_jing [] = {"��","��","��","��","��","��","��","��","��","��","��","��","��","�","��","��","��","��","��","��","��","��","��","��","��","��","��","�","��","��","��"};
	final static String han_jian [] = {"��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��"};
	final static String han_juan [] = {"��","��","��","��","��","�","��","Ȧ","��"};
	final static String han_jia [] = {"��","��","��","��","٤","��","��","��","��","��","��","��","��","��","��","��","��","��","��"};
	final static String han_jie [] = {"��","��","��","��","��","��","��","��","��","��","ڵ","��","��","��","��","��","��","��","��","��","��","��","��","��","��"};
	final static String han_jiu [] = {"��","��","��","��","��","��","�","��","��","��","��","��","��","��","��","��"};
	final static String han_jin [] = {"��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��"};
	final static String han_jue [] = {"��","��","��","��","��","��","��","��","��","��"};
	final static String han_jun [] = {"��","��","��","��","��","��","��","��","��","��"};
	final static String han_ju [] = {"��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","�","��","��","��","��"};
	final static String han_ji [] = {"��","��","��","��","��","��","ߴ","��","��","��","��","��","��","��","��","��","��","�","��","��","��","��","��","��","��","��","��","��","��","��","��","��","�","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","�","�","��","��","��"};
	final static String han_kuang [] = {"��","��","��","��","ڲ","��","ڿ","��","��","��"};
	final static String han_keng [] = {"��","��"};
	final static String han_kong [] = {"��","��","��","��","��"};
	final static String han_kuai [] = {"��","��","��","��","��","��"};
	final static String han_kuan [] = {"��","��"};
	final static String han_kang [] = {"��","��","��","��","��","��","��"};
	final static String han_kai [] = {"��","��","��","��","��","��","��","��"};
	final static String han_kou [] = {"��","ߵ","��","��","��"};
	final static String han_kua [] = {"��","��","��","��","��"};
	final static String han_kao [] = {"��","��","��","��","��","��"};
	final static String han_ken [] = {"��","��","��","��"};
	final static String han_kan [] = {"��","��","٩","��","��","��","��","��"};
	final static String han_kui [] = {"��","��","��","��","��","��","��","��","��","��","��","��"};
	final static String han_kun [] = {"��","��","��","��"};
	final static String han_kuo [] = {"��","��","��","��"};
	final static String han_ke [] = {"��","��","��","�","��","��","��","��","��","��","��","��","�","��","��","��","��","��","��","��","��"};
	final static String han_ku [] = {"��","��","��","�","��","��","��","��","��"};
	final static String han_ka [] = {"��","��","��","��","��"};
	final static String han_huang [] = {"��","��","��","��","��","��","��","��","��","��","��","��","��"};
	final static String han_heng [] = {"��","��","��","��","��","��"};
	final static String han_hong [] = {"��","��","��","��","��","��","��","��","��","��"};
	final static String han_huai [] = {"��","��","��","��","��","��","��"};
	final static String han_huan [] = {"��","��","��","��","��","��","��","ѣ","��","��","��","��","��"};
	final static String han_hang [] = {"��","��","��","��"};
	final static String han_han [] = {"��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","�","��","��","��","��","��","�"};
	final static String han_hai [] = {"��","��","��","��","��","��","��","��"};
	final static String han_hou [] = {"��","��","��","��","��","��","��"};
	final static String han_hua [] = {"��","��","��","��","��","��","��","��","��","��"};
	final static String han_hao [] = {"��","��","�","��","��","�","��","��","�","��","��","��","��","��"};
	final static String han_hei [] = {"��","��"};
	final static String han_hen [] = {"��","��","��","��"};
	final static String han_hui [] = {"��","��","��","��","��","��","��","ڶ","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��"};
	final static String han_hun [] = {"��","ڻ","��","��","��","��","��","��"};
	final static String han_huo [] = {"��","��","��","��","��","��","��","��","��","��","��","޽"};
	final static String han_ha [] = {"��","Ϻ","��","��"};
	final static String han_hu [] = {"��","��","��","Ϸ","��","��","��","��","��","��","��","��","�","��","��","��","��","��","��","��","��","��","��","��"};
	final static String han_he [] = {"��","��","��","��","ڭ","��","��","��","��","��","��","��","��","��","��","�","��","��","��","��"};
	final static String han_wang [] = {"��","��","��","��","��","��","��","��","��"};
	final static String han_weng [] = {"��","��","��"};
	final static String han_wai [] = {"��","��"};
	final static String han_wei [] = {"��","��","Τ","Ϊ","δ","Σ","ΰ","α","λ","Υ","γ","β","Χ","�","ί","ζ","η","��","θ","Ω","ά","ν","ή","Ψ","�","ξ","μ","��","��","ι","�","΢","ο","κ"};
	final static String han_wen [] = {"��","��","��","��","��","��","��","��","��","��","��","��","��","��"};
	final static String han_wan [] = {"��","��","��","��","��","��","ݸ","��","��","��","��","��","��","��","��","��"};
	final static String han_wa [] = {"��","��","��","��","��","��","�","��"};
	final static String han_wo [] = {"��","��","��","��","��","ݫ","�","��","��"};
	final static String han_wu [] = {"��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��"};
	final static String han_tang [] = {"��","��","��","��","��","��","�","��","��","��","��","��","��","��","��","�"};
	final static String han_teng [] = {"��","��","��"};
	final static String han_tian [] = {"��","��","��","��","��","��","��","��","��"};
	final static String han_tiao [] = {"��","٬","��","��","��","��","��","��","�","��","��"};
	final static String han_ting [] = {"��","͡","��","ͤ","ͥ","ͦ","ͣ","��","ͧ","��","��"};
	final static String han_tong [] = {"ͬ","١","ͮ","��","ͳ","�","��","��","ͩ","ͱ","ͨ","Ͱ","ͭ","ͯ","ʹ","Ͳ"};
	final static String han_tuan [] = {"��"};
	final static String han_tie [] = {"��","��","��"};
	final static String han_tan [] = {"̾","̳","��","̰","�","̹","̿","̸","̽","��","��","̺","̲","̯","̵","̼","̷","̶","̱"};
	final static String han_tai [] = {"̫","̨","̭","̬","��","̦","̧","̥","��","̩","��"};
	final static String han_tou [] = {"ͷ","Ͷ","͸","͵"};
	final static String han_tao [] = {"��","߶","��","��","��","��","��","��","��","��","��","��","�"};
	final static String han_tui [] = {"߯","��","��","��","��","��","��"};
	final static String han_tun [] = {"��","��","�","��","��","��","��"};
	final static String han_tuo [] = {"��","��","��","��","��","��","��","��","˵","��","��","��"};
	final static String han_te [] = {"��","߯","��"};
	final static String han_ta [] = {"��","��","��","��","��","�","��","��","�","̤","̡","̣"};
	final static String han_ti [] = {"��","��","��","��","��","��","��","��","��","��","��","��","��"};
	final static String han_tu [] = {"��","͹","��","ͺ","ͼ","��","ͻ","Ϳ",";","ͽ","ݱ","��"};
	final static String han_shuang [] = {"˫","ˬ","˪"};
	final static String han_sheng [] = {"��","ʥ","��","��","��","ʤ","ʡ","��","��","��","ʢ","ʣ","��"};
	final static String han_shuai [] = {"˧","˦","˥","��","ˤ","�"};
	final static String han_shuan [] = {"��","˩","˨","��"};
	final static String han_shang [] = {"��","��","��","��","��","��","��","��"};
	final static String han_shao [] = {"��","��","��","��","��","��","��","��","��","��","��","��","��","��"};
	final static String han_shei [] = {};
	final static String han_shen [] = {"ʲ","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��"};
	final static String han_seng [] = {"ɮ"};
	final static String han_shou [] = {"��","��","��","��","��","��","��","��","��","��","��","��"};
	final static String han_shua [] = {"ˢ","ˣ","�"};
	final static String han_shai [] = {"ɹ","ɸ"};
	final static String han_shan [] = {"ɽ","��","ڨ","��","ɾ","ɼ","��","��","�","��","��","ɺ","դ","��","��","��","��","��","ɿ","��","��","��","��","��"};
	final static String han_sang [] = {"ɥ","ɣ","ɤ","��"};
	final static String han_shui [] = {"ˮ","˵","˭","˰","˯"};
	final static String han_shun [] = {"˱","˳","˴","˲"};
	final static String han_shuo [] = {"˸","˵","˷","˶"};
	final static String han_song [] = {"��","��","��","��","��","��","��","��","��","��"};
	final static String han_suan [] = {"��","��","��"};
	final static String han_she [] = {"��","��","��","��","��","��","ʰ","��","��","��","��","��","��","��","��","��"};
	final static String han_sha [] = {"ɱ","ɳ","ɴ","ɼ","ɲ","ɰ","ɯ","��","ɶ","��","��","ɵ","ɷ","��","��"};
	final static String han_sai [] = {"��","��","��","��","��"};
	final static String han_sao [] = {"ɨ","ɦ","ɧ","ɩ","��","��"};
	final static String han_shi [] = {"ʮ","ʬ","ʿ","��","ʲ","ʾ","��","��","ʧ","��","ʷ","ʸ","ʯ","ʽ","ʦ","��","ʶ","ʱ","��","��","ʫ","��","ʹ","��","��","��","ʻ","ʵ","��","��","ʴ","��","��","ʳ","ʨ","��","ʺ","��","ʩ","ʰ","��","��","��","ʪ","��"};
	final static String han_sen [] = {"ɭ"};
	final static String han_shu [] = {"��","��","��","��","��","��","��","��","��","ˡ","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��"};
	final static String han_sou [] = {"�","��","��","�","��","��","��"};
	final static String han_san [] = {"��","ɡ","ɢ"};
	final static String han_sui [] = {"��","��","��","��","��","��","��","��","��","��","��"};
	final static String han_sun [] = {"��","��","��","��"};
	final static String han_suo [] = {"��","ɯ","��","��","�","��","��","��","��","��","��"};
	final static String han_si [] = {"˿","˾","��","��","��","��","˽","��","��","��","��","ʳ","˼","˹","��","˺","˻"};
	final static String han_se [] = {"ɫ","ɬ","ɪ","��",};
	final static String han_sa [] = {"��","��","�","��","��"};
	final static String han_su [] = {"��","��","��","��","��","��","��","��","��","��","��","��","��"};
	final static String han_rang [] = {"��","��","��"};
	final static String han_reng [] = {"��","��"};
	final static String han_rong [] = {"��","��","��","��","��","��","��","��","��","��","��"};
	final static String han_ruan [] = {"��","��"};
	final static String han_ran [] = {"Ƚ","��","Ⱦ","Ȼ","ȼ"};
	final static String han_rao [] = {"��","��","�"};
	final static String han_rou [] = {"��","��","��","��"};
	final static String han_ren [] = {"��","��","��","��","��","��","��","�","��"};
	final static String han_rui [] = {"��","��","��","�","��"};
	final static String han_run [] = {"��","��"};
	final static String han_ruo [] = {"��","��"};
	final static String han_ri [] = {"��"};
	final static String han_ru [] = {"��","��","��","��","��","��","��","��"};
	final static String han_re [] = {"��","��","��"};
	final static String han_qiang [] = {"Ǽ","Ǻ","��","ǹ","��","ǿ","ǻ","ǽ","��","Ǿ","��"};
	final static String han_qiong [] = {"��","�","��"};
	final static String han_qiao [] = {"��","��","��","��","��","��","ڽ","��","��","��","��","��","��","�","��","��","��","��","��"};
	final static String han_qing [] = {"��","��","��","��","��","��","��","��","ٻ","��","��","��","��","��","��","��","��","��"};
	final static String han_qian [] = {"ǧ","Ƿ","Ǫ","ܷ","Ǩ","��","ǳ","ǥ","ǰ","��","ǣ","Ǧ","Ǯ","ǯ","ٻ","Ǭ","ǵ","Ƕ","ǫ","ǲ","ǩ","�","Ǹ","��","Ǵ","Ǳ","ǭ"};
	final static String han_quan [] = {"Ȱ","Ȯ","ȫ","Ȩ","��","ڹ","ȯ","Ȫ","ȭ","Ȭ","Ȧ","��"};
	final static String han_qia [] = {"��","Ǣ","ǡ","��"};
	final static String han_qie [] = {"��","��","��","�","��","��","��"};
	final static String han_qiu [] = {"��","��","��","��","��","��","��","��","��","��","��","�","��","��"};
	final static String han_qin [] = {"��","��","��","��","��","��","��","��","��","��","��","��","��","��","��"};
	final static String han_que [] = {"ȴ","ȱ","ȸ","ȷ","ȵ","ȳ"};
	final static String han_qun [] = {"ȹ","Ⱥ"};
	final static String han_qu [] = {"��","ȥ","��","��","�","��","ȡ","��","��","��","Ȣ","��","��","��","Ȥ"};
	final static String han_qi [] = {"��","��","��","��","��","��","��","��","��","�","��","��","��","��","��","�","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","�","�","��","��","��","��","��","��","��","��","��","��","��","��","��","��","�","��"};
	final static String han_pang [] = {"��","��","��","��","��","��","��","��","�"};
	final static String han_peng [] = {"��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��"};
	final static String han_pian [] = {"Ƭ","��","��","��","ƫ","ƭ","��","ƪ","��"};
	final static String han_piao [] = {"��","Ʊ","��","��","��","Ư","��","Ʈ","�","ư"};
	final static String han_ping [] = {"ƽ","��","ƹ","��","ƻ","ƾ","ƺ","��","��","ƿ","Ƽ"};
	final static String han_pen [] = {"��","��"};
	final static String han_pan [] = {"��","��","��","��","��","��","��","��","��","��","��","��","��","�","��"};
	final static String han_pai [] = {"��","��","��","��","ٽ","��","��","��","��"};
	final static String han_pao [] = {"��","��","��","��","��","��","��","��","��","��"};
	final static String han_pie [] = {"Ʋ","Ƴ"};
	final static String han_pin [] = {"��","ƶ","ƴ","Ʒ","�","Ƶ","Ƹ","��","�"};
	final static String han_pei [] = {"��","��","��","��","��","��","��","��","��"};
	final static String han_pou [] = {"��","��"};
	final static String han_pa [] = {"��","��","��","��","��","��","ſ","��","ž","��"};
	final static String han_po [] = {"��","��","��","��","��","��","��","��","��","��","��","۶","��"};
	final static String han_pi [] = {"ƥ","Ƥ","ا","�","ƨ","��","��","��","��","ƣ","ơ","Ʀ","��","Ƣ","��","��","��","Ƨ","Ʃ","��"};
	final static String han_pu [] = {"��","��","��","��","��","��","��","��","��","��","��","��","��","��","�","��"};
	final static String han_zhuang [] = {"ׯ","ױ","׳","״","׮","װ","ײ","��"};
	final static String han_zheng [] = {"��","��","֤","��","ں","֣","��","��","�","��","��","��","֢","��","�","��","��","��","��"};
	final static String han_zhong [] = {"��","��","��","��","��","��","��","��","��","��","��"};
	final static String han_zhuai [] = {"ק"};
	final static String han_zhuan [] = {"ר","��","ת","ש","׬","׭","׫"};
	final static String han_zhang [] = {"��","��","��","��","��","��","��","��","��","��","��","��","�","�"};
	final static String han_zhei [] = {};
	final static String han_zhen [] = {"��","��","��","��","��","��","��","��","֡","��","��","��","��","��","��","��","�","��","��"};
	final static String han_zeng [] = {"��","��","��","��"};
	final static String han_zhai [] = {"լ","��","��","��","��","խ","ի","ծ","ժ","կ"};
	final static String han_zhou [] = {"��","��","��","��","��","�","��","��","��","ף","��","��","��","��","��","��"};
	final static String han_zhua [] = {"צ","ץ"};
	final static String han_zhan [] = {"ռ","մ","ն","ձ","ջ","ս","չ","վ","յ","ո","��","ճ","տ","��","ղ","շ"};
	final static String han_zang [] = {"��","��","��","��","��"};
	final static String han_zhao [] = {"צ","��","��","��","گ","��","��","��","��","��","��","��","��","��","��"};
	final static String han_zhui [] = {"׹","׷","׺","׵","�","׶","׸"};
	final static String han_zhun [] = {"׻","׼"};
	final static String han_zhuo [] = {"��","׾","��","׿","��","׽","��","��","��","��","��","��"};
	final static String han_zong [] = {"��","��","��","��","��","��","��"};
	final static String han_zuan [] = {"��","߬","��"};
	final static String han_zen [] = {"��"};
	final static String han_zhe [] = {"��","��","��","��","��","��","��","��","��","��","��","ߡ","��"};
	final static String han_zan [] = {"��","��","��","��","��"};
	final static String han_zha [] = {"��","��","է","��","߸","թ","զ","բ","ը","գ","դ","��","��","��","ա","��","��","ե"};
	final static String han_zai [] = {"��","��","��","��","��","��","��","��","��"};
	final static String han_zhi [] = {"֮","֧","ֹ","֭","ֻ","ִ","֥","ּ","��","־","ֽ","ַ","��","֨","ʶ","��","ֶ","ֱ","֪","��","֯","��","��","֦","��","��","֫","��","ָ","��","��","ֵ","��","ֿ","��","֬","ְ","��","��","ֺ","��","��","ֳ","��","ֲ","��","��","��","��","֩"};
	final static String han_zao [] = {"��","��","��","��","��","��","��","��","��","��","��","��","��","��","��"};
	final static String han_zei [] = {"��"};
	final static String han_zou [] = {"��","��","��","��","��","��","��","��","۸"};
	final static String han_zhu [] = {"��","��","��","ס","��","��","��","ע","��","٪","��","פ","��","��","��","ף","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��"};
	final static String han_zui [] = {"��","��","��","��","��"};
	final static String han_zun [] = {"��","��"};
	final static String han_zuo [] = {"��","��","��","��","��","��","��","��"};
	final static String han_zi [] = {"��","��","��","��","�","��","֨","��","��","��","��","��","��","��","��"};
	final static String han_ze [] = {"��","��","��","��","��","զ","��","��"};
	final static String han_za [] = {"��","��","��","զ","��"};
	final static String han_zu [] = {"��","��","��","��","��","��","��","��"};
	final static String han_yang [] = {"��","��","��","��","��","�","��","��","��","��","��","��","��","��","��","��","��","��"};
	final static String han_ying [] = {"ӭ","Ӧ","Ӣ","ӯ","ӳ","ӫ","ݺ","Ө","Ӫ","Ӥ","��","Ӳ","ӱ","Ӭ","�","ӧ","Ӱ","ӣ","��","Ӯ","ӥ"};
	final static String han_yong [] = {"��","��","Ӷ","ӽ","ӵ","Ӿ","��","ٸ","ӿ","��","ӹ","Ӽ","ӻ"};
	final static String han_yuan [] = {"Ԫ","Զ","Ա","԰","��","Է","�","Թ","Ժ","Բ","ԭ","ԩ","ԧ","Ԭ","Ԩ","Ԯ","Ե","��","Դ","Գ","ԯ","Ը"};
	final static String han_yan [] = {"��","��","��","��","��","��","��","��","��","ٲ","��","��","��","��","Ǧ","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��"};
	final static String han_yao [] = {"ز","ߺ","Լ","��","��","ű","��","��","Կ","Ҫ","ҩ","Ҧ","ҧ","��","Ҩ","�","Ҥ","ҥ","ң","��","ҡ","��","��","ҫ"};
	final static String han_you [] = {"��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��"};
	final static String han_yin [] = {"��","��","ӡ","��","��","��","��","��","��","��","��","��","��","�","��","��","��","��","��","��","�"};
	final static String han_yue [] = {"Ի","��","��","Լ","��","Կ","˵","��","��","Ծ","Խ","��"};
	final static String han_yun [] = {"��","��","��","��","ܿ","��","Ա","��","��","��","��","��","�","��","��","��"};
	final static String han_ya [] = {"Ѿ","��","��","��","ѹ","��","߹","ѽ","ѿ","Ѻ","ѻ","��","Ѽ","�","��","��","��","��","��"};
	final static String han_yu [] = {"��","��","Ԧ","��","��","��","��","��","��","��","��","��","�","��","��","��","��","��","��","خ","��","��","��","��","��","Ԥ","ԡ","��","��","��","��","��","��","��","��","��","��","��","��","��","Ԣ","ԣ","��","�","��","��","��","ԥ"};
	final static String han_ye [] = {"Ҳ","ҵ","Ҷ","а","ү","ҷ","ҳ","��","ұ","ҹ","Ү","��","ק","��","��","��","Ҵ","��","Һ","��","Ұ","Ҭ","Ҹ","��","ҭ"};
	final static String han_yo [] = {"Ӵ"};
	final static String han_yi [] = {"һ","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","ҽ","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","�","��","�","��","��","��","��","Ҿ","��","��","��","��","��","��","��","��","��","��","��","��","��"};
	final static String han_xiang [] = {"��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��"};
	final static String han_xiong [] = {"��","��","��","��","��","��","��"};
	final static String han_xiao [] = {"С","Т","Ф","��","��","��","��","У","��","Ц","Ч","��","��","��","��","Х","��","��","��","��","��","��","��"};
	final static String han_xing [] = {"��","��","��","��","��","��","��","��","��","��","��","ʡ","�","��","��","��","��"};
	final static String han_xian [] = {"��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","��","�","��","��","��","��","��","��","��","��","��","��","��","޺"};
	final static String han_xuan [] = {"��","��","ѡ","��","Ѥ","��","ѣ","��","��","��","��","��","��","�","Ѣ"};
	final static String han_xia [] = {"��","��","ϻ","��","��","��","��","Ͽ","��","Ϻ","��","��","Ͻ","Ϲ","ϼ"};
	final static String han_xie [] = {"д","Ҷ","а","Э","Ѫ","Щ","й","к","в","Ю","ж","��","м","б","е","г","л","Ш","Ъ","Я","��","Ь","Ы","и"};
	final static String han_xiu [] = {"��","��","��","��","��","��","��","��","��","��","��","��","��"};
	final static String han_xin [] = {"��","��","о","��","��","�","��","ݷ","��","п","��","н","ܰ","��"};
	final static String han_xue [] = {"Ѩ","Ѫ","ѧ","��","ѩ","ѥ","Ѧ"};
	final static String han_xun [] = {"Ѷ","ѵ","Ѳ","Ѹ","Ѱ","ѱ","Ѵ","Ѯ","ѯ","ѫ","ѷ","��","ѳ","��","ѭ","Ѭ","��","޹"};
	final static String han_xu [] = {"��","��","��","��","��","��","ڼ","��","��","��","��","�","��","��","��","��","��","��","��","��","��","��","��","��","��","��"};
	final static String han_xi [] = {"ϰ","Ϧ","Ϸ","��","ϫ","��","ϣ","ϵ","ϸ","��","��","ϴ","��","��","Ϣ","��","��","��","��","ϯ","ϧ","Ϯ","��","Ϥ","��","��","ϲ","϶","��","Ϭ","ϡ","Ϫ","�","��","ϱ","��","Ϩ","��","ϥ","��","��","�"};

	
	static {
		han = new HashMap<String, String []>();
		han.put("fang",han_fang);
		han.put("feng",han_feng);
		han.put("fei",han_fei);
		han.put("fen",han_fen);
		han.put("fan",han_fan);
		han.put("fou",han_fou);
		han.put("fo",han_fo);
		han.put("fa",han_fa);
		han.put("fu",han_fu);
		han.put("guang",han_guang);
		han.put("geng",han_geng);
		han.put("gong",han_gong);
		han.put("guai",han_guai);
		han.put("guan",han_guan);
		han.put("gang",han_gang);
		han.put("gan",han_gan);
		han.put("gai",han_gai);
		han.put("gou",han_gou);
		han.put("gua",han_gua);
		han.put("gao",han_gao);
		han.put("gei",han_gei);
		han.put("gen",han_gen);
		han.put("gui",han_gui);
		han.put("gun",han_gun);
		han.put("guo",han_guo);
		han.put("ga",han_ga);
		han.put("gu",han_gu);
		han.put("ge",han_ge);
		han.put("dang",han_dang);
		han.put("deng",han_deng);
		han.put("dian",han_dian);
		han.put("diao",han_diao);
		han.put("ding",han_ding);
		han.put("dong",han_dong);
		han.put("duan",han_duan);
		han.put("dia",han_dia);
		han.put("dai",han_dai);
		han.put("dao",han_dao);
		han.put("die",han_die);
		han.put("den",han_den);
		han.put("diu",han_diu);
		han.put("dei",han_dei);
		han.put("dou",han_dou);
		han.put("dan",han_dan);
		han.put("dui",han_dui);
		han.put("dun",han_dun);
		han.put("duo",han_duo);
		han.put("di",han_di);
		han.put("de",han_de);
		han.put("da",han_da);
		han.put("du",han_du);
		han.put("eng",han_eng);
		han.put("en",han_en);
		han.put("ei",han_ei);
		han.put("er",han_er);
		han.put("e",han_e);
		han.put("bang",han_bang);
		han.put("beng",han_beng);
		han.put("bing",han_bing);
		han.put("bian",han_bian);
		han.put("bai",han_bai);
		han.put("ban",han_ban);
		han.put("bao",han_bao);
		han.put("bei",han_bei);
		han.put("ben",han_ben);
		han.put("bie",han_bie);
		han.put("bin",han_bin);
		han.put("bi",han_bi);
		han.put("bo",han_bo);
		han.put("bu",han_bu);
		han.put("ba",han_ba);
		han.put("chuang",han_chuang);
		han.put("chang",han_chang);
		han.put("cheng",han_cheng);
		han.put("chong",han_chong);
		han.put("chuan",han_chuan);
		han.put("chuai",han_chuai);
		han.put("ceng",han_ceng);
		han.put("cang",han_cang);
		han.put("cong",han_cong);
		han.put("chai",han_chai);
		han.put("chan",han_chan);
		han.put("chao",han_chao);
		han.put("cuan",han_cuan);
		han.put("chen",han_chen);
		han.put("chou",han_chou);
		han.put("chua",han_chua);
		han.put("chui",han_chui);
		han.put("chun",han_chun);
		han.put("chuo",han_chuo);
		han.put("chi",han_chi);
		han.put("cou",han_cou);
		han.put("chu",han_chu);
		han.put("che",han_che);
		han.put("cha",han_cha);
		han.put("cui",han_cui);
		han.put("cun",han_cun);
		han.put("cuo",han_cuo);
		han.put("can",han_can);
		han.put("cai",han_cai);
		han.put("cen",han_cen);
		han.put("cao",han_cao);
		han.put("ca",han_ca);
		han.put("ce",han_ce);
		han.put("cu",han_cu);
		han.put("ci",han_ci);
		han.put("ang",han_ang);
		han.put("an",han_an);
		han.put("ao",han_ao);
		han.put("ai",han_ai);
		han.put("a",han_a);
		han.put("niang",han_niang);
		han.put("neng",han_neng);
		han.put("nian",han_nian);
		han.put("nang",han_nang);
		han.put("niao",han_niao);
		han.put("ning",han_ning);
		han.put("nong",han_nong);
		han.put("nuan",han_nuan);
		han.put("nao",han_nao);
		han.put("nei",han_nei);
		han.put("nie",han_nie);
		han.put("nin",han_nin);
		han.put("nen",han_nen);
		han.put("niu",han_niu);
		han.put("nan",han_nan);
		han.put("nou",han_nou);
		han.put("nai",han_nai);
//		han.put("n��e",han_n��e);
		han.put("nuo",han_nuo);
		han.put("nun",han_nun);
		han.put("nu",han_nu);
//		han.put("n��",han_n��);
		han.put("na",han_na);
		han.put("ng",han_ng);
		han.put("ni",han_ni);
		han.put("ne",han_ne);
		han.put("ou",han_ou);
		han.put("o",han_o);
		han.put("liang",han_liang);
		han.put("leng",han_leng);
		han.put("lian",han_lian);
		han.put("lang",han_lang);
		han.put("liao",han_liao);
		han.put("ling",han_ling);
		han.put("long",han_long);
		han.put("luan",han_luan);
		han.put("lao",han_lao);
		han.put("lei",han_lei);
		han.put("lie",han_lie);
		han.put("lin",han_lin);
		han.put("lan",han_lan);
		han.put("liu",han_liu);
		han.put("lia",han_lia);
		han.put("lou",han_lou);
		han.put("lai",han_lai);
		han.put("lue",han_lue);
//		han.put("l��e",han_l��e);
		han.put("lun",han_lun);
		han.put("luo",han_luo);
		han.put("le",han_le);
		han.put("li",han_li);
		han.put("la",han_la);
		han.put("lu",han_lu);
//		han.put("l��",han_l��);
		han.put("mang",han_mang);
		han.put("meng",han_meng);
		han.put("mian",han_mian);
		han.put("miao",han_miao);
		han.put("ming",han_ming);
		han.put("men",han_men);
		han.put("man",han_man);
		han.put("mai",han_mai);
		han.put("mao",han_mao);
		han.put("mie",han_mie);
		han.put("min",han_min);
		han.put("mei",han_mei);
		han.put("miu",han_miu);
		han.put("mou",han_mou);
		han.put("ma",han_ma);
		han.put("mi",han_mi);
		han.put("mo",han_mo);
		han.put("me",han_me);
		han.put("mu",han_mu);
		han.put("jiang",han_jiang);
		han.put("jiong",han_jiong);
		han.put("jiao",han_jiao);
		han.put("jing",han_jing);
		han.put("jian",han_jian);
		han.put("juan",han_juan);
		han.put("jia",han_jia);
		han.put("jie",han_jie);
		han.put("jiu",han_jiu);
		han.put("jin",han_jin);
		han.put("jue",han_jue);
		han.put("jun",han_jun);
		han.put("ju",han_ju);
		han.put("ji",han_ji);
		han.put("kuang",han_kuang);
		han.put("keng",han_keng);
		han.put("kong",han_kong);
		han.put("kuai",han_kuai);
		han.put("kuan",han_kuan);
		han.put("kang",han_kang);
		han.put("kai",han_kai);
		han.put("kou",han_kou);
		han.put("kua",han_kua);
		han.put("kao",han_kao);
		han.put("ken",han_ken);
		han.put("kan",han_kan);
		han.put("kui",han_kui);
		han.put("kun",han_kun);
		han.put("kuo",han_kuo);
		han.put("ke",han_ke);
		han.put("ku",han_ku);
		han.put("ka",han_ka);
		han.put("huang",han_huang);
		han.put("heng",han_heng);
		han.put("hong",han_hong);
		han.put("huai",han_huai);
		han.put("huan",han_huan);
		han.put("hang",han_hang);
		han.put("han",han_han);
		han.put("hai",han_hai);
		han.put("hou",han_hou);
		han.put("hua",han_hua);
		han.put("hao",han_hao);
		han.put("hei",han_hei);
		han.put("hen",han_hen);
		han.put("hui",han_hui);
		han.put("hun",han_hun);
		han.put("huo",han_huo);
		han.put("ha",han_ha);
		han.put("hu",han_hu);
		han.put("he",han_he);
		han.put("wang",han_wang);
		han.put("weng",han_weng);
		han.put("wai",han_wai);
		han.put("wei",han_wei);
		han.put("wen",han_wen);
		han.put("wan",han_wan);
		han.put("wa",han_wa);
		han.put("wo",han_wo);
		han.put("wu",han_wu);
		han.put("tang",han_tang);
		han.put("teng",han_teng);
		han.put("tian",han_tian);
		han.put("tiao",han_tiao);
		han.put("ting",han_ting);
		han.put("tong",han_tong);
		han.put("tuan",han_tuan);
		han.put("tie",han_tie);
		han.put("tan",han_tan);
		han.put("tai",han_tai);
		han.put("tou",han_tou);
		han.put("tao",han_tao);
		han.put("tui",han_tui);
		han.put("tun",han_tun);
		han.put("tuo",han_tuo);
		han.put("te",han_te);
		han.put("ta",han_ta);
		han.put("ti",han_ti);
		han.put("tu",han_tu);
		han.put("shuang",han_shuang);
		han.put("sheng",han_sheng);
		han.put("shuai",han_shuai);
		han.put("shuan",han_shuan);
		han.put("shang",han_shang);
		han.put("shao",han_shao);
		han.put("shei",han_shei);
		han.put("shen",han_shen);
		han.put("seng",han_seng);
		han.put("shou",han_shou);
		han.put("shua",han_shua);
		han.put("shai",han_shai);
		han.put("shan",han_shan);
		han.put("sang",han_sang);
		han.put("shui",han_shui);
		han.put("shun",han_shun);
		han.put("shuo",han_shuo);
		han.put("song",han_song);
		han.put("suan",han_suan);
		han.put("she",han_she);
		han.put("sha",han_sha);
		han.put("sai",han_sai);
		han.put("sao",han_sao);
		han.put("shi",han_shi);
		han.put("sen",han_sen);
		han.put("shu",han_shu);
		han.put("sou",han_sou);
		han.put("san",han_san);
		han.put("sui",han_sui);
		han.put("sun",han_sun);
		han.put("suo",han_suo);
		han.put("si",han_si);
		han.put("se",han_se);
		han.put("sa",han_sa);
		han.put("su",han_su);
		han.put("rang",han_rang);
		han.put("reng",han_reng);
		han.put("rong",han_rong);
		han.put("ruan",han_ruan);
		han.put("ran",han_ran);
		han.put("rao",han_rao);
		han.put("rou",han_rou);
		han.put("ren",han_ren);
		han.put("rui",han_rui);
		han.put("run",han_run);
		han.put("ruo",han_ruo);
		han.put("ri",han_ri);
		han.put("ru",han_ru);
		han.put("re",han_re);
		han.put("qiang",han_qiang);
		han.put("qiong",han_qiong);
		han.put("qiao",han_qiao);
		han.put("qing",han_qing);
		han.put("qian",han_qian);
		han.put("quan",han_quan);
		han.put("qia",han_qia);
		han.put("qie",han_qie);
		han.put("qiu",han_qiu);
		han.put("qin",han_qin);
		han.put("que",han_que);
		han.put("qun",han_qun);
		han.put("qu",han_qu);
		han.put("qi",han_qi);
		han.put("pang",han_pang);
		han.put("peng",han_peng);
		han.put("pian",han_pian);
		han.put("piao",han_piao);
		han.put("ping",han_ping);
		han.put("pen",han_pen);
		han.put("pan",han_pan);
		han.put("pai",han_pai);
		han.put("pao",han_pao);
		han.put("pie",han_pie);
		han.put("pin",han_pin);
		han.put("pei",han_pei);
		han.put("pou",han_pou);
		han.put("pa",han_pa);
		han.put("po",han_po);
		han.put("pi",han_pi);
		han.put("pu",han_pu);
		han.put("zhuang",han_zhuang);
		han.put("zheng",han_zheng);
		han.put("zhong",han_zhong);
		han.put("zhuai",han_zhuai);
		han.put("zhuan",han_zhuan);
		han.put("zhang",han_zhang);
		han.put("zhei",han_zhei);
		han.put("zhen",han_zhen);
		han.put("zeng",han_zeng);
		han.put("zhai",han_zhai);
		han.put("zhou",han_zhou);
		han.put("zhua",han_zhua);
		han.put("zhan",han_zhan);
		han.put("zang",han_zang);
		han.put("zhao",han_zhao);
		han.put("zhui",han_zhui);
		han.put("zhun",han_zhun);
		han.put("zhuo",han_zhuo);
		han.put("zong",han_zong);
		han.put("zuan",han_zuan);
		han.put("zen",han_zen);
		han.put("zhe",han_zhe);
		han.put("zan",han_zan);
		han.put("zha",han_zha);
		han.put("zai",han_zai);
		han.put("zhi",han_zhi);
		han.put("zao",han_zao);
		han.put("zei",han_zei);
		han.put("zou",han_zou);
		han.put("zhu",han_zhu);
		han.put("zui",han_zui);
		han.put("zun",han_zun);
		han.put("zuo",han_zuo);
		han.put("zi",han_zi);
		han.put("ze",han_ze);
		han.put("za",han_za);
		han.put("zu",han_zu);
		han.put("yang",han_yang);
		han.put("ying",han_ying);
		han.put("yong",han_yong);
		han.put("yuan",han_yuan);
		han.put("yan",han_yan);
		han.put("yao",han_yao);
		han.put("you",han_you);
		han.put("yin",han_yin);
		han.put("yue",han_yue);
		han.put("yun",han_yun);
		han.put("ya",han_ya);
		han.put("yu",han_yu);
		han.put("ye",han_ye);
		han.put("yo",han_yo);
		han.put("yi",han_yi);
		han.put("xiang",han_xiang);
		han.put("xiong",han_xiong);
		han.put("xiao",han_xiao);
		han.put("xing",han_xing);
		han.put("xian",han_xian);
		han.put("xuan",han_xuan);
		han.put("xia",han_xia);
		han.put("xie",han_xie);
		han.put("xiu",han_xiu);
		han.put("xin",han_xin);
		han.put("xue",han_xue);
		han.put("xun",han_xun);
		han.put("xu",han_xu);
		han.put("xi",han_xi);


	}
	
	

}
